image: node:alpine

stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules
    - dist

install:
  stage: install
  script:
    - pnpm i
    - echo '安装依赖完成'

test: 
  stage: test
  script:
    - pnpm coverage
    - echo '测试完成'

    
build: 
  stage: build
  script:
    - pnpm build
    - echo '打包完成'